--Team NERDS: Cristian Fitzgerald, Shelby Simpson; CS305-71: Fall 2018

--drop.SQL Version 2

--To drop the tables created in create.sql

--Based on: create.sql

--added drop of ComputeCurvedGradePercent() and ComputeCurvedGradeLetter() functions
--added drop of Before_Submission_Insert_Compute_Percent and Before_Submission_Insert_Compute_Letter triggers

--spool results
\o spoolDrop.txt

--Suppress notices when running scripts
SET client_min_messages TO WARNING;

--Diagnostics:
\qecho -n 'Script run on '
\qecho -n `date /t`
\qecho -n 'at '
\qecho `time /t`
\qecho -n 'Script run by ' :USER ' on server ' :HOST ' with db ' :DBNAME
\qecho ' '
\qecho --------------

--Drop DB objects created in createTables.sql
\qecho Dropping table Course...
DROP TABLE nerds.Course CASCADE;
\qecho Dropping table Season...
DROP TABLE nerds.Season CASCADE;
\qecho Dropping table Term...
DROP TABLE nerds.Term CASCADE;
\qecho Dropping table Instructor...
DROP TABLE nerds.Instructor CASCADE;
\qecho Dropping table Section...
DROP TABLE nerds.Section CASCADE;
\qecho Dropping table Grade...
DROP TABLE nerds.Grade CASCADE;
\qecho Dropping table Grade_Tier...
DROP TABLE nerds.Grade_Tier CASCADE;
\qecho Dropping table Student...
DROP TABLE nerds.Student CASCADE;
\qecho Dropping table Enrollee...
DROP TABLE nerds.Enrollee CASCADE;
\qecho Dropping table AttendanceStatus...
DROP TABLE nerds.AttendanceStatus CASCADE;
\qecho Dropping table AttendanceRecord...
DROP TABLE nerds.AttendanceRecord CASCADE;
\qecho Dropping table Assessment_Kind...
DROP TABLE nerds.Assessment_Kind CASCADE;
\qecho Dropping table Assessment_Item...
DROP TABLE nerds.Assessment_Item CASCADE;
\qecho Dropping table Submission...
DROP TABLE nerds.Submission CASCADE;

--Drop DB objects created in userRoleMgmt.sql
SET ROLE 'nerds';
\qecho Dropping User nerds_test_student...
DROP USER nerds_test_student;
\qecho Dropping User nerds_test_instructor...
DROP USER nerds_test_instructor;
\qecho Dropping User john_cena...
DROP USER nerds_john_cena;
\qecho Dropping User mickey_mouse...
DROP USER nerds_mickey_mouse;
\qecho Dropping User nerds_test_deptHead...
DROP USER nerds_test_deptHead;
\qecho Dropping user role nerds_student_role...
DROP ROLE IF EXISTS nerds_student_role;
\qecho Dropping user role nerds_instructor_role
DROP ROLE IF EXISTS nerds_instructor_role;
\qecho Dropping user role nerds_deptHead_role...
DROP ROLE IF EXISTS nerds_deptHead_role;
RESET ROLE;


--Drop DB objects created in gradeTierMgmt.sql
\qecho Dropping Trigger Before_Grade_Tier_Insert_Range...
DROP TRIGGER IF EXISTS Before_Grade_Tier_Insert_Range ON nerds.Grade_Tier;
\qecho Dropping Trigger After_Grade_Tier_Update_Range...
DROP TRIGGER IF EXISTS After_Grade_Tier_Update_Range ON nerds.Grade_Tier;
\qecho Dropping Function addSectionGradeTier...
DROP FUNCTION IF EXISTS nerds.addSectionGradeTier(INTEGER, VARCHAR(2), NUMERIC(5,2), NUMERIC(5,2)) CASCADE;
\qecho Dropping Function dropSectionGradeTier...
DROP FUNCTION IF EXISTS nerds.dropSectionGradeTier(INTEGER, VARCHAR(2)) CASCADE;
\qecho Dropping Function getSectionGradeTiers...
DROP FUNCTION IF EXISTS nerds.getSectionGradeTiers(IN INTEGER, OUT VARCHAR(2), OUT NUMERIC(5,2), OUT NUMERIC(5,2)) CASCADE;
\qecho Dropping Function modifySectionGradeTier...
DROP FUNCTION IF EXISTS nerds.modifySectionGradeTier(INTEGER, VARCHAR(2), NUMERIC(5,2), NUMERIC(5,2), VARCHAR(2)) CASCADE;
\qecho Dropping Function copySectionGradeTier...
DROP FUNCTION IF EXISTS nerds.copySectionGradeTier(INTEGER, VARCHAR(2), INTEGER) CASCADE;
\qecho Dropping Function CheckRange...
DROP FUNCTION IF EXISTS nerds.CheckRange() CASCADE;

--Drop DB objects created in assessmentKindMgmt.sql
\qecho Dropping Function addSectionAssessmentKind...
DROP FUNCTION IF EXISTS nerds.addSectionAssessmentKind(INTEGER,VARCHAR(20),VARCHAR(100),NUMERIC(3,2)) CASCADE;
\qecho Dropping Function dropSectionAssessmentKind...
DROP FUNCTION IF EXISTS nerds.dropSectionAssessmentKind(INTEGER,VARCHAR(20)) CASCADE;
\qecho Dropping Function getSectionAssessmentKinds...
DROP FUNCTION IF EXISTS nerds.getSectionAssessmentKinds(INTEGER) CASCADE;
\qecho Dropping Function modifySectionAssessmentKind...
DROP FUNCTION IF EXISTS nerds.modifySectionAssessmentKind(INTEGER,VARCHAR(20),VARCHAR(100),NUMERIC(5,2),VARCHAR(20)) CASCADE;
\qecho Dropping Function copySectionAssessmentKind...
DROP FUNCTION IF EXISTS nerds.copySectionAssessmentKind(INTEGER,VARCHAR(20),INTEGER) CASCADE;

--Drop DB objects created in assessmentItemMgmt.sql
\qecho Dropping Trigger Before_Assessment_Item_Insert_RevealDate...
DROP TRIGGER IF EXISTS Before_Assessment_Item_Insert_RevealDate ON nerds.Assessment_Item;
\qecho Dropping Trigger Before_Assessment_Item_Insert_Curve...
DROP TRIGGER IF EXISTS Before_Assessment_Item_Insert_Curve ON nerds.Assessment_Item;
\qecho Dropping Function CheckRevealDate...
DROP FUNCTION nerds.CheckRevealDate() CASCADE;
\qecho Dropping Function DefaultCurve...
DROP FUNCTION IF EXISTS DefaultCurve() CASCADE;
\qecho Dropping Function addSectionAssessmentItem...
DROP FUNCTION IF EXISTS nerds.addSectionAssessmentItem(INTEGER, VARCHAR(20), INTEGER, VARCHAR(100), NUMERIC(5,2), DATE, DATE, DATE, NUMERIC(3,2)) CASCADE;
\qecho Dropping Function dropSectionAssessmentItem...
DROP FUNCTION IF EXISTS nerds.dropSectionAssessmentItem(INTEGER, VARCHAR(20), INTEGER) CASCADE;
\qecho Dropping Function getSectionAssessmentItems...
DROP FUNCTION IF EXISTS nerds.getSectionAssessmentItems(INTEGER, VARCHAR(20)) CASCADE;
\qecho Dropping Function modifySectionAssessmentItem...
DROP FUNCTION IF EXISTS nerds.modifySectionAssessmentItem(INTEGER, VARCHAR(20), INTEGER, VARCHAR(100), NUMERIC(5,2), DATE, DATE, DATE, NUMERIC(3,2), INTEGER) CASCADE;

--Drop DB objects created in submissionMgmt.sql
\qecho Dropping Trigger Before_Submission_Insert_Points...
DROP TRIGGER IF EXISTS Before_Submission_Insert_Points ON nerds.Submission;
\qecho Dropping Trigger Before_Submission_Insert_Dates...
DROP TRIGGER IF EXISTS Before_Submission_Insert_Dates ON nerds.Submission;
\qecho Dropping Trigger Before_Submission_Insert_Compute_Percent...
DROP TRIGGER IF EXISTS Before_Submission_Insert_Compute_Percent ON nerds.Submission;
\qecho Dropping Trigger Before_Submission_Insert_Compute_Letter...
DROP TRIGGER IF EXISTS Before_Submission_Insert_Compute_Letter ON nerds.Submission;
\qecho Dropping Trigger Before_Submission_Insert_Extra...
DROP TRIGGER IF EXISTS Before_Submission_Insert_Extra ON nerds.Submission;
\qecho Dropping Trigger Before_Submission_Insert_Penalty...
DROP TRIGGER IF EXISTS Before_Submission_Insert_Penalty ON nerds.Submission;
\qecho Dropping Function CompareBasePoints...
DROP FUNCTION nerds.CompareBasePoints() CASCADE;
\qecho Dropping Function CompareDates...
DROP FUNCTION nerds.CompareDates() CASCADE;
\qecho Dropping Function ComputeCurvedGradeLetter...
DROP FUNCTION nerds.ComputeCurvedGradeLetter() CASCADE;
\qecho Dropping Function ComputeCurvedGradePercent...
DROP FUNCTION nerds.ComputeCurvedGradePercent() CASCADE;
\qecho Dropping Function DefaultExtraCreditEarned...
DROP FUNCTION nerds.DefaultExtraCreditEarned() CASCADE;
\qecho Dropping Function DefaultPenalty...
DROP FUNCTION nerds.DefaultPenalty() CASCADE;
\qecho Dropping Function addSubmission...
DROP FUNCTION IF EXISTS nerds.addSubmission(INTEGER, INTEGER, VARCHAR(20), INTEGER, NUMERIC(5,2), NUMERIC(5,2), NUMERIC(5,2), DATE, VARCHAR(50)) CASCADE;
\qecho Dropping Function getAssessmentItemScoresEnrollee...
DROP FUNCTION IF EXISTS nerds.getAssessmentItemScoresEnrollee(INTEGER, VARCHAR(20), INTEGER) CASCADE;
\qecho Dropping Function getAssessmentItemScoresInstructor...
DROP FUNCTION IF EXISTS nerds.getAssessmentItemScoresInstructor(INTEGER, VARCHAR(20), INTEGER) CASCADE;
\qecho Dropping Function getAssessmentKindAvgEnrollee...
DROP FUNCTION IF EXISTS nerds.getAssessmentKindAvgEnrollee(INTEGER,INTEGER,VARCHAR(20)) CASCADE;
\qecho Dropping Function getAssessmentKindAvgInstructor...
DROP FUNCTION IF EXISTS nerds.getAssessmentKindAvgInstructor(INTEGER, VARCHAR(20)) CASCADE;
\qecho Dropping Function modifySubmission...
DROP FUNCTION IF EXISTS nerds.modifySubmission(INTEGER, INTEGER, VARCHAR(20), INTEGER, NUMERIC(5,2), NUMERIC(5,2), NUMERIC(5,2), DATE, VARCHAR(50)) CASCADE;
\qecho Dropping Function getEnrollees...
DROP FUNCTION IF EXISTS nerds.getEnrollees(INTEGER) CASCADE;

--end spooling
\o